AllCops:
  RunRailsCops: true
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundBody:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/AndOr:
  Enabled: false
