language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.1.3
  - ruby-head

script: CODECLIMATE_REPO_TOKEN=694646784ed8d9bbd332f9c6e86e9d44cc8617cbb5526a125f442f760af59816 bundle exec rspec spec

matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: 2.1
    - rvm: ruby-head
